name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  release:
    name: Plugin Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build Plugin
      run: make dist
    - name: WordPress Plugin Deploy
      uses: akshitsethi/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: customize-woo
