on: push
name: Tests

jobs:
  tests:
    name: Plugin Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Dependencies
      run: make install
    - name: Lint
      run: make fmt
